### ISSUE TITLE
Compatibility with Ruby 2.2.x

### ISSUE THREAD

**Issue by phene** [rondevera/twig#49]
Your JSON dependency doesn't support Ruby 2.2.x, but they've added support with this: https://github.com/flori/json/issues/229. You may want to upgrade.

**Comment by martyzz1** [comment]
yeah this is causing me grief too...

**Comment by rondevera** [comment]
This is covered by #47, and will be part of the Twig 1.8 release (in progress). Sorry for the hassle!

**Comment by rondevera** [comment]
Released with Twig 1.7.1.
